source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'iota' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'iotaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  ENVFILES = {
    'Debug' => '.env.test',
    'Release' => '.env',
  }
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config' && config.name == 'Debug'
          # 配置：ENVFILE，Release不用配置，因为该配置优先级会高于脚本中环境变量设置，build脚本输出test包会读取配置.env
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end
  end
end
